#!/bin/env bash
#Bash script that transfers a file from our client to a server:
#Check if all required parameters are provided
if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
# Assign parameters to variables
	LOCAL_FILE=$1
	IP=$2
	USERNAME=$3
	PRIVATE_KEY=$4
# Transfer the file using SCP with the specified parameters
	scp -o StrictHostKeyChecking=no -i "$PRIVATE_KEY" "$LOCAL_FILE" "$USERNAME@$IP":~/
fi
