#!/usr/bin/env bash
# script that pings an IP address passed as an argument.
IP_ADDRESS=$1
if [ -z "$IP_ADDRESS" ]; then
	echo "5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

ping -c 5 $IP_ADDRESS
